{
 "title": "social-network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(social_network_request_seconds_count[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, method, uri) (rate(social_network_request_seconds_bucket[1m])))*1000",
     "legendFormat": "0.5 {{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, method, uri) (rate(social_network_request_seconds_bucket[1m])))*1000",
     "legendFormat": "0.95 {{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, method, uri) (rate(social_network_request_seconds_bucket[1m])))*1000",
     "legendFormat": "0.99 {{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(1, sum by (le, method, uri) (rate(social_network_request_seconds_bucket[1m])))*1000",
     "legendFormat": "1 {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "internal error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(social_network_request_seconds_count{status=~\"5\\\\d\\\\d\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "4xx error",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(social_network_request_seconds_count{status=~\"4\\\\d\\\\d\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}